"""Map FPL short codes to football-data.co.uk team names."""

DEFAULT_ALIASES: dict[str, str] = {
    "ARS": "Arsenal",
    "AVL": "Aston Villa",
    "BOU": "Bournemouth",
    "BRE": "Brentford",
    "BHA": "Brighton",
    "BUR": "Burnley",
    "CHE": "Chelsea",
    "CRY": "Crystal Palace",
    "EVE": "Everton",
    "FUL": "Fulham",
    "IPS": "Ipswich",
    "LEI": "Leicester",
    "LIV": "Liverpool",
    "LUT": "Luton",
    "MCI": "Man City",
    "MUN": "Man United",
    "NEW": "Newcastle",
    "NFO": "Nott'm Forest",
    "SHU": "Sheffield United",
    "SOU": "Southampton",
    "SUN": "Sunderland",
    "TOT": "Tottenham",
    "WHU": "West Ham",
    "WOL": "Wolves",
    "LEEDS": "Leeds",
    "NOR": "Norwich",
    "WAT": "Watford",
    "WBA": "West Brom",
    "CARD": "Cardiff",
    "HUD": "Huddersfield",
    "SWA": "Swansea",
    "STO": "Stoke",
}
